final-project-insider/BACK-LOGIN

- final/src/main/java/com/insider/login/commute/dto/CommuteDTO.java
- final/src/main/java/com/insider/login/commute/dto/UpdateTimeOfCommuteDTO.java
- final/src/main/java/com/insider/login/commute/entity/Commute.java
- final/src/main/java/com/insider/login/commute/service/CommuteService.java
- final/src/test/java/com/insider/login/commute/controller/CommuteControllerTests.java
- final/src/test/java/com/insider/login/commute/service/CommuteServiceTests.java
퇴근 시간, 총 근무 시간, 근무 상태에 대한 update  TEST 완료하였습니다.
> feat #2 - [출퇴근] 퇴근 시간 등록 (출퇴근 update) TEST 완료

- .idea/modules.xml
- .idea/modules/final.main.iml
- final/src/main/java/com/insider/login/approval/service/ApprovalService.java
- final/src/test/java/com/insider/login/approval/service/ApprovalServiceTest.java
> Feat#2전자결재기안테스트

- final/src/main/java/com/insider/login/common/ResponseMessage.java
- final/src/main/java/com/insider/login/commute/controller/CommuteController.java
- final/src/main/java/com/insider/login/commute/dto/CommuteDTO.java
- final/src/main/java/com/insider/login/commute/entity/Commute.java
- final/src/main/java/com/insider/login/commute/repository/CommuteRepository.java
- final/src/main/java/com/insider/login/commute/service/CommuteService.java
- final/src/main/java/com/insider/login/member/dto/DepartmentDTO.java
- final/src/main/java/com/insider/login/member/dto/MemberDTO.java
- final/src/main/java/com/insider/login/member/entity/Department.java
- final/src/main/java/com/insider/login/member/entity/Member.java
- final/src/test/java/com/insider/login/commute/controller/CommuteControllerTests.java
- final/src/test/java/com/insider/login/commute/service/CommuteServiceTests.java
feat #4 - [출퇴근] 출퇴근 내역 조회 TEST 완료
fix #5 - [출퇴근] 부서별 출퇴근 내역 조회 TEST 완료
> feat #4 - [출퇴근] 출퇴근 내역 조회 TEST 완료

- final/src/main/java/com/insider/login/member/dto/MemberDTO.java
> merge하고 수정

- final/http/approval/approval.http
- final/src/main/java/com/insider/login/approval/builder/ApprovalBuilder.java
- final/src/main/java/com/insider/login/approval/builder/ApproverBuilder.java
- final/src/main/java/com/insider/login/approval/controller/ApprovalController.java
- final/src/main/java/com/insider/login/approval/dto/ApprovalDTO.java
- final/src/main/java/com/insider/login/approval/dto/ApproverDTO.java
- final/src/main/java/com/insider/login/approval/dto/DepartmentDTO.java
- final/src/main/java/com/insider/login/approval/dto/MemberDTO.java
- final/src/main/java/com/insider/login/approval/dto/ReferencerDTO.java
- final/src/main/java/com/insider/login/approval/dto/ResponseDTO.java
- final/src/main/java/com/insider/login/approval/entity/Approval.java
- final/src/main/java/com/insider/login/approval/entity/Department.java
- final/src/main/java/com/insider/login/approval/entity/Member.java
- final/src/main/java/com/insider/login/approval/repository/ApprovalRepository.java
- final/src/main/java/com/insider/login/approval/repository/ApproverRepository.java
- final/src/main/java/com/insider/login/approval/repository/AttachmentRepository.java
- final/src/main/java/com/insider/login/approval/repository/DepartmentRepository.java
- final/src/main/java/com/insider/login/approval/repository/FormRepository.java
- final/src/main/java/com/insider/login/approval/repository/MemberRepository.java
- final/src/main/java/com/insider/login/approval/repository/ReferencerRepository.java
- final/src/main/java/com/insider/login/approval/service/ApprovalService.java
- final/src/test/java/com/insider/login/approval/service/ApprovalServiceTest.java
Feat#7 전자결재회수 및 코드 수정
수정한 부분 : 한건의 전자결재를 조회할 때마다 전자결재에 대한 모든 정보를 가져오도록 했는데, 이때 '처리 중' 이 없는 건에 대해 null 처리를 함
> Feat#7 전자결재회수

- final/src/main/java/com/insider/login/leave/entity/LeaveMember.java
- final/src/main/java/com/insider/login/leave/repository/LeaveMemberRepository.java
- final/src/main/java/com/insider/login/leave/service/LeaveService.java
dh-04-30-004
feat #15 - [휴가] 휴가 신청내역 조회 컨트롤러 작성
dh-05-01-001
feat #16 - [휴가] 휴가 신청 컨트롤러
feat #17 - [휴가] 휴가 신청 취소 
feat #18 - [휴가] 휴가 취소 요청
feat #19 - [휴가] 발생 내역 조회
feat #20 - [휴가] 휴가 발생
feat #21 - [휴가] 상세 조회
dh-05-01-002
feat #22 - [휴가] 휴가 처리 서비스 리팩토링
feat #23 - [휴가] 휴가 신청 컨트롤러
feat #24 - [휴가] 휴가 신청 취소 컨트롤러
feat #25 - [휴가] 발생 내역 조회
feat #26 - [휴가] 휴가 취소 요청 리팩토링
feat #27 - [휴가] 휴가 발생 컨트롤러
feat #28 - [휴가] 상세 조회 컨트롤러
feat #29 - [휴가] 휴가 신청 처리
feat #30 - [휴가] 휴가 보유 내역 조회
dh-05-01-003
feat #2 - [캘린더] 일정등록
feat #3 - [캘린더] 일정 수정
feat #4 - [캘린더] 일정 삭제
dh-05-02-001
feat #1 - [캘린더] 일정 조회
dh-05-02-002
feat #1 - [캘린더] 일정 조회
dh-05-02-003
feat #5 - [캘린더] 일정 조회 컨트롤러
feat #6 - [캘린더] 일정 등록 컨트롤러
feat #7 - [캘린더] 일정 수정 컨트롤러
feat #8 - [캘린더] 휴가 삭제 컨트롤러
dh-05-02-004
eat #9 - [캘린더] http 요청
dh-05-02-005
feat #1 - …
> feat #5 - [휴가, 일정, 수요조사]  휴가, 일정, 수요조사 관련

- final/src/main/java/com/insider/login/approval/controller/ApprovalController.java
- final/src/test/java/com/insider/login/approval/controller/ApprovalControllerTest.java
- final/src/test/java/com/insider/login/calendar/controller/CalendarControllerTests.java
> Feat#16 전자결재controller회수테스트

- final/src/main/java/com/insider/login/leave/controller/LeaveController.java
- final/src/main/java/com/insider/login/leave/entity/LeaveSubmit.java
- final/src/main/java/com/insider/login/leave/util/LeaveUtil.java
> 차감일수 계산식에 +1을 하여 시작일을 포함한 일수를 계산하도록 하였습니다.
> fix #35 - [휴가] 휴가 차감 일수 계산식 수정

- final/http/approval/approval.http
- final/src/main/java/com/insider/login/approval/controller/ApprovalController.java
- final/src/main/java/com/insider/login/approval/repository/ApprovalRepository.java
- final/src/main/java/com/insider/login/approval/service/ApprovalService.java
- final/src/main/java/com/insider/login/auth/filter/JwtAuthorizationFilter.java
> fix#5 전자결재 목록조회 page 수정

- final/src/main/java/com/insider/login/leave/service/LeaveService.java
> 휴가 취소 신청 메소드를 휴가 신청 메소드에 조건을 달아 병합하였습니다.
> feat #36 - [휴가] 서비스 클래스 리팩토링

- final/src/main/java/com/insider/login/approval/repository/ApprovalRepository.java
> fix#6 전자결재 목록조회 임시저장 수정

- final/src/main/java/com/insider/login/leave/controller/LeaveController.java
- final/src/main/java/com/insider/login/leave/dto/LeaveAccrualDTO.java
- final/src/main/java/com/insider/login/leave/entity/LeaveAccrual.java
- final/src/main/java/com/insider/login/leave/service/LeaveService.java
> 휴가 발생 조회 시 서비스에서 클라이언트로 보낼 DTO 설정 과정에 발생 내역의 사번을 통해 해당 사번의 이름을 DTO에 추가하는 과정을 추가
> 휴가 발생 등록 시 현재 일자를 함께 저장하는 코드 추가
> feat #37 - [휴가] 휴가 발생 조회, 등록 수정

- final/src/main/java/com/insider/login/leave/controller/LeaveController.java
- final/src/main/java/com/insider/login/leave/service/LeaveService.java
> fix #38 - [휴가] 휴가 신청 취소 코드 복구

- final/src/main/java/com/insider/login/leave/entity/Leaves.java
- final/src/main/java/com/insider/login/leave/service/LeaveService.java
> 휴가 발생 등록 시 save한 엔티티를 반환받아서 대상자 사번, 발생 일수를 얻어와 휴가 내역에 특별휴가로 저장하는 기능을 추가하였습니다.
> feat #39 - [휴가] 휴가 발생 등록 시 휴가 내역 추가

- final/src/main/java/com/insider/login/member/controller/MemberController.java
- final/src/main/java/com/insider/login/member/entity/Member.java
- final/src/main/java/com/insider/login/position/controller/PositionController.java
- final/src/main/java/com/insider/login/position/dto/PositionDTOSecond.java
- final/src/main/java/com/insider/login/position/entity/Position.java
- final/src/main/java/com/insider/login/position/repository/PositionRepository.java
- final/src/main/java/com/insider/login/position/service/PositionService.java
> DB수정으로 인해 code 수정

- final/src/main/java/com/insider/login/leave/controller/LeaveController.java
- final/src/main/java/com/insider/login/leave/dto/LeaveMemberDTO.java
- final/src/main/java/com/insider/login/leave/entity/LeaveMember.java
- final/src/main/java/com/insider/login/leave/repository/LeaveMemberRepository.java
- final/src/main/java/com/insider/login/leave/service/LeaveService.java
> 클라이언트에서 요청 받은 단어를 사원명에 포함하는 멤버를 조회할 수 있습니다.
> 조회된 멤버가 가지고 있는 부서 코드를 통해 부서명도 함께 DTO에 담아 클라이언트로 응답을 보냅니다.
> feat #40 - [휴가] 휴가 발생 등록

- final/src/main/java/com/insider/login/approval/dto/MemberDTO.java
- final/src/main/java/com/insider/login/approval/dto/PositionDTO.java
- final/src/main/java/com/insider/login/approval/entity/Member.java
- final/src/main/java/com/insider/login/approval/entity/Position.java
- final/src/main/java/com/insider/login/approval/repository/ApprovalDepartmentRepository.java
- final/src/main/java/com/insider/login/approval/repository/ApprovalMemberRepository.java
- final/src/main/java/com/insider/login/approval/repository/ApprovalPositionRepository.java
- final/src/main/java/com/insider/login/approval/repository/ApprovalRepository.java
- final/src/main/java/com/insider/login/approval/service/ApprovalService.java
- final/src/test/java/com/insider/login/approval/service/ApprovalServiceTest.java
Fix#7전자결재직급조회관련수정 및 관련 레포지토리 class -> interface 로 refactoring
> Fix#7전자결재직급조회관련수정

- final/src/main/java/com/insider/login/commute/dto/CommuteMemberDTO.java
- final/src/main/java/com/insider/login/commute/entity/CommuteMember.java
position_info 테이블의 pk 변동으로 매핑 설정 변경하였습니다.
> feat #23 - [출퇴근] position db 설정 변동으로 entity와 dto 매핑 변경

- final/src/main/java/com/insider/login/auth/filter/HeaderFilter.java
- final/src/main/java/com/insider/login/auth/filter/JwtAuthorizationFilter.java
- final/src/main/java/com/insider/login/common/utils/TokenUtils.java
- final/src/main/java/com/insider/login/department/controller/DepartmentController.java
- final/src/main/java/com/insider/login/department/dto/DepartmentChangeNameDTO.java
- final/src/main/java/com/insider/login/department/repository/DepartmentRepository.java
- final/src/main/java/com/insider/login/department/service/DepartmentService.java
- final/src/main/java/com/insider/login/position/controller/PositionController.java
- final/src/main/java/com/insider/login/position/dto/PositionChangeNameDTO.java
- final/src/main/java/com/insider/login/position/repository/PositionRepository.java
- final/src/main/java/com/insider/login/position/service/PositionService.java
- final/src/main/resources/application.yml
- 부서, 직급 CRUD 기능 구현
- 존재하는 부서는 삭제 불가능
- 부서명을 2번 입력하는데 일치하지 않으면 삭제 불가능
- 존재하지 않는 부서는 "부서가 존재하지 않습니다 메세지" 출력
직급
- 직급을 등록할 때 직급명, 레벨 둘다 같이 입력을 해서 등록을 합니다
- 직급명 변경 기능 구현
- 직급은 자유롭게 삭제 가능
> 부서, 직급 CRUD 기능 구현

- final/src/main/java/com/insider/login/leave/controller/LeaveController.java
> 조회 시 page 응답명을 통일하여 클라이언트에서 모든 기능을 하나의 액션으로 처리할 수 있도록 수정하였습니다.
> feat #41 - [휴가] 조회 시 page 응답명 통일

- final/src/main/java/com/insider/login/leave/controller/LeaveController.java
> PathVariable로 받던 휴가 신청 번호를 바디에 포함시켜 가져오도록 수정하였습니다.
> feat #42 - [휴가] 휴가 컨트롤러 수정

- final/src/main/java/com/insider/login/calendar/controller/CalendarContorller.java
- final/src/main/java/com/insider/login/leave/controller/LeaveController.java
- final/src/main/java/com/insider/login/leave/dto/LeaveInfoDTO.java
- final/src/main/java/com/insider/login/leave/repository/LeaveRepository.java
- final/src/main/java/com/insider/login/leave/service/LeaveService.java
- final/src/main/java/com/insider/login/leave/util/LeaveUtil.java
> 반복문을 사용하던 코드를 stream을 사용해 코드를 간략하게 최적화 하였습니다.
> 페이징을 시도할 때 중복 제거와 페이징을 같이 수행하지 않아 페이징이 제대로 수행되지 않아 쿼리문에서 DISTINCT를 사용하여 중복 제거와 페이징을 동시에 수행하도록 하였습니다.
> feat #44 - [휴가] 휴가 정보 계산 리팩토링

- final/src/main/java/com/insider/login/leave/service/LeaveService.java
> 휴가 정보 조회 시 사번을 통해 이름을 조회해와서 dto에 담아 함께 반환하는 로직을 추가하였습니다.
> feat #45 - [휴가] 휴가 정보 계산 시 사번으로 이름 조회해서 추가

- final/http/note/note.http
- final/src/main/java/com/insider/login/auth/filter/JwtAuthorizationFilter.java
- final/src/main/java/com/insider/login/insite/controller/InsiteController.java
- final/src/main/java/com/insider/login/insite/entity/InsiteMember.java
- final/src/main/java/com/insider/login/insite/entity/insiteCommute/InsiteCommute.java
- final/src/main/java/com/insider/login/insite/entity/insiteDepart/InsiteDepartment.java
- final/src/main/java/com/insider/login/insite/entity/insiteLeave/insiteLeave.java
- final/src/main/java/com/insider/login/insite/repository/InsiteRepository.java
- final/src/main/java/com/insider/login/insite/service/InsiteService.java
- final/src/main/resources/application.yml
> 통계 나머지 2개 마무리하였습니다.
> 금일 출근자 현황
> 금일 휴가자 현황
> feat #2 - [통계] 금일 출근 현황 / 금일 휴가자 현황

- final/src/main/java/com/insider/login/survey/controller/SurveyController.java
- final/src/main/java/com/insider/login/survey/dto/SurveyDTO.java
- final/src/main/java/com/insider/login/survey/service/SurveyService.java
- final/src/test/java/com/insider/login/survey/service/SurveyServiceTests.java
> 멤버 아이디를 클라이언트에서 받기 때문에 컨트롤러에서 응답번호와 사번을 DTO 통합해서 받도록 수정하였습니다.
> feat #15 - [수요조사] 등록 로직 리팩토링

- final/src/main/java/com/insider/login/commute/dto/CorrectionAndCommuteDTO.java
- final/src/main/java/com/insider/login/commute/dto/CorrectionDTO.java
- final/src/main/java/com/insider/login/commute/repository/CommuteRepository.java
- final/src/main/java/com/insider/login/commute/repository/CorrectionAndCommuteRepository.java
- final/src/main/java/com/insider/login/commute/repository/CorrectionRepository.java
- final/src/main/java/com/insider/login/commute/service/CommuteService.java
출퇴근 내역 조회 /정정 내역 조회 중 JPA 쿼리 오류 이슈 진행중입니다.
> fix #26 - [출퇴근] 출퇴근 내역 조회 /정정 내역 조회 중 JPA 쿼리 오류 이슈

- final/src/main/java/com/insider/login/commute/builder/CommuteBuilder.java
- final/src/main/java/com/insider/login/commute/controller/CommuteController.java
- final/src/main/java/com/insider/login/commute/dto/CommuteDTO.java
- final/src/main/java/com/insider/login/commute/dto/CommuteDepartmentDTO.java
- final/src/main/java/com/insider/login/commute/dto/CommuteMemberDTO.java
- final/src/main/java/com/insider/login/commute/dto/CorrectionDTO.java
- final/src/main/java/com/insider/login/commute/entity/Commute.java
- final/src/main/java/com/insider/login/commute/entity/CommuteDepartment.java
- final/src/main/java/com/insider/login/commute/entity/CommuteMember.java
- final/src/main/java/com/insider/login/commute/entity/Correction.java
- final/src/main/java/com/insider/login/commute/repository/CommuteDepartmentRepository.java
- final/src/main/java/com/insider/login/commute/repository/CommuteMemberRepository.java
- final/src/main/java/com/insider/login/commute/repository/CommuteRepository.java
- final/src/main/java/com/insider/login/commute/repository/CorrectionRepository.java
- final/src/main/java/com/insider/login/commute/service/CommuteService.java
- final/src/main/java/com/insider/login/config/BeanConfig.java
- final/src/main/java/com/insider/login/other/notice/controller/NoticeController.java
- final/src/test/java/com/insider/login/commute/controller/CommuteControllerTests.java
- final/src/test/java/com/insider/login/commute/service/CommuteServiceTests.java
commute 엔티티와 correction 엔티티, CommuteMember 엔티티, CommuteDepartment 엔티티의 매핑 수정하여,
서비스단에서 전반적으로 코드 수정, 이슈 해결하였습니다.
> fix #27 - [출퇴근] 매핑 수정으로 서비스 전반적인 코드 수정

- final/src/main/java/com/insider/login/department/controller/DepartmentController.java
- final/src/main/java/com/insider/login/member/dto/MemberDTO.java
- final/src/main/java/com/insider/login/member/dto/ShowMemberDTO.java
- final/src/main/java/com/insider/login/member/entity/Member.java
- final/src/main/java/com/insider/login/member/repository/MemberRepository.java
- final/src/main/java/com/insider/login/member/service/MemberService.java
- final/src/main/java/com/insider/login/position/controller/PositionController.java
- final/src/main/java/com/insider/login/position/dto/PositionDetailsDTO.java
- final/src/main/resources/application.yml
> 구성원 성별 생년월일 정보 추가

- final/src/main/java/com/insider/login/calendar/controller/CalendarContorller.java
- final/src/main/java/com/insider/login/leave/dto/LeaveInfoDTO.java
- final/src/main/java/com/insider/login/leave/service/LeaveService.java
- final/src/main/java/com/insider/login/leave/util/LeaveUtil.java
- final/src/test/java/com/insider/login/leave/service/LeavesServiceTests.java
> 휴가 취소 신청 시 상위 신청의 처리 상태를 승인으로 다시 돌려놓도록 로직을 수정하였습니다.
> feat #47 - [휴가] 휴가 취소 신청 로직 리팩토링

- final/http/approval/approval.http
- final/src/main/java/com/insider/login/approval/controller/ApprovalController.java
- final/src/main/java/com/insider/login/approval/service/ApprovalService.java
- final/src/main/resources/application.yml
- final/src/test/java/com/insider/login/leave/service/LeavesServiceTests.java
> Fix#5전자결재관련yml수정

- final/src/main/java/com/insider/login/leave/service/LeaveService.java
> 휴가 신청 반려 시 승인으로 변경되던 것을 취소반려로 변경하였습니다.
> 서비스 처리 로직에서 불필요한 부분을 줄이고 최적화하는 리팩토링을 진행하였습니다.
> fix #48 - [휴가] 휴가 신청 로직 처리

- final/src/main/java/com/insider/login/calendar/service/CalendarService.java
> feat #14 - [캘린더] 전체 부서 일정 조회 로직

- final/http/approval/approval.http
- final/src/main/java/com/insider/login/approval/controller/ApprovalController.java
- final/src/main/java/com/insider/login/approval/dto/ApprovalDTO.java
- final/src/main/java/com/insider/login/approval/dto/AttachmentDTO.java
- final/src/main/java/com/insider/login/approval/repository/ApprovalRepository.java
- final/src/main/java/com/insider/login/approval/repository/ApproverRepository.java
- final/src/main/java/com/insider/login/approval/repository/AttachmentRepository.java
- final/src/main/java/com/insider/login/approval/repository/ReferencerRepository.java
- final/src/main/java/com/insider/login/approval/service/ApprovalService.java
- final/src/test/java/com/insider/login/approval/controller/ApprovalControllerTest.java
- final/src/test/java/com/insider/login/approval/service/ApprovalServiceTest.java
- final/src/test/java/com/insider/login/commute/controller/CommuteControllerTests.java
fix#3 전자결재 반려날짜 및 repository 전면 수정
> fix#3 전자결재 반려날짜 및 repository 전면 수정

- final/src/main/java/com/insider/login/approval/repository/ApproverRepository.java
- final/src/main/java/com/insider/login/approval/service/ApprovalService.java
- final/src/test/java/com/insider/login/approval/service/ApprovalServiceTest.java
> Fix#9 전자결재반려날짜

- .idea/dataSources.xml
- .idea/vcs.xml
- final/http/user/user.http
- final/src/main/java/com/insider/login/insite/controller/InsiteController.java
- final/src/main/java/com/insider/login/insite/entity/InsiteMember.java
- final/src/main/java/com/insider/login/insite/repository/InsiteRepository.java
- final/src/main/java/com/insider/login/insite/service/InsiteService.java
- final/src/main/resources/application.yml
- final/src/test/java/com/insider/login/leave/service/LeavesServiceTests.java
> 금일 휴가자 + 금일 출근자 통계 합치기 -> 금일 출근 여부를 휴가와 함께 보여줌으로써 더욱 통계치 확실히 하기 위함.
> 휴가 출근의 합침으로 인한 new 통계, 구성원 생년월일이 추가된 것을 통한 월별 생일자 / 금주 생일자 / 금일 생일자 표시
> feat #4 - [통계] 전체적인 리팩토링

- final/src/main/java/com/insider/login/leave/dto/SubmitAndCalendarDTO.java
- final/src/main/java/com/insider/login/leave/entity/LeaveMember.java
- final/src/main/java/com/insider/login/leave/entity/SubmitAndCalendar.java
- final/src/main/java/com/insider/login/leave/repository/LeaveCalendarRepository.java
- final/src/main/java/com/insider/login/leave/repository/LeaveDepartmentRepository.java
- final/src/main/java/com/insider/login/leave/repository/LeaveMemberRepository.java
- final/src/main/java/com/insider/login/leave/repository/LeavePositionRepository.java
- final/src/main/java/com/insider/login/leave/repository/SubmitAndCalendarRepository.java
- final/src/main/java/com/insider/login/leave/service/LeaveService.java
> 휴가 신청 승인 시 해당 신청의 시작 일자와 종료일자로 새로운 일정을 등록합니다.
> 일정의 제목은 신청자의 부서, 이름, 직급 휴가 로 구성됩니다.
> 휴가 취소 신청 승인 시 해당 신청의 상위 신청 승인 시 등록됐던 일정을 삭제합니다.
> feat #31 - [휴가] 휴가 처리 시 발생 이벤트

- final/http/approval/approval.http
- final/src/main/java/com/insider/login/approval/builder/ApproverBuilder.java
- final/src/main/java/com/insider/login/approval/builder/AttachmentBuilder.java
- final/src/main/java/com/insider/login/approval/builder/ReferencerBuilder.java
- final/src/main/java/com/insider/login/approval/controller/ApprovalController.java
- final/src/main/java/com/insider/login/approval/repository/ApproverRepository.java
- final/src/main/java/com/insider/login/approval/service/ApprovalService.java
- final/src/test/java/com/insider/login/approval/service/ApprovalServiceTest.java
> feat#21 전자결재 임시저장 재저장

- final/src/main/java/com/insider/login/approval/controller/ApprovalController.java
- final/src/main/java/com/insider/login/approval/service/ApprovalService.java
> fix#9 전자결재 재임시저장 수정

- .idea/dataSources.xml
- final/src/main/java/com/insider/login/commute/controller/CommuteController.java
- final/src/main/java/com/insider/login/commute/service/CommuteService.java
출퇴근 내역이 없을 때 출퇴근 정정 등록 시, 처리하는 로직 추가하였습니다.
> feat #30 - [출퇴근] 출퇴근 내역이 없을 때 출퇴근 정정 등록 시, 처리하는 로직

- final/src/main/java/com/insider/login/insite/controller/InsiteController.java
- final/src/main/java/com/insider/login/insite/repository/InsiteRepository.java
- final/src/main/java/com/insider/login/insite/service/InsiteService.java
기존엔 전체 미처리 상신건수를 보여줬지만, 수정하여 결재선에 따라 숫자가 보여지도록 수정
> feat #6 - [통계] 메인페이지 상신인 조건 추가

- final/http/approval/approval.http
- final/src/main/java/com/insider/login/approval/controller/ApprovalController.java
- final/src/main/java/com/insider/login/approval/repository/ApprovalMemberRepository.java
> feat#22 파일 다운로드

- final/src/main/java/com/insider/login/approval/controller/ApprovalController.java
- final/src/main/java/com/insider/login/approval/service/ApprovalService.java
> Fix#10 전자결재 임시저장 후 기안 수정

- final/src/main/java/com/insider/login/leave/controller/LeaveController.java
- final/src/main/java/com/insider/login/leave/dto/LeaveAccrualDTO.java
- final/src/main/java/com/insider/login/leave/service/LeaveService.java
> 신청 처리와 일정 등록까지 처리하도록 로직을 수정하였습니다.
> 발생 처리 된 휴가는 대상자의 휴가 신청 내역에 특별휴가로 보여지며 처리 상태는 발생입니다.
> feat #50 - [휴가] 휴가 발생 로직 수정
